# Generated by Django 3.1.4 on 2020-12-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('facebook_link', models.CharField(max_length=50)),
                ('linkedin_link', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='media/team/%Y/')),
            ],
        ),
    ]
