# Generated by Django 3.1.4 on 2020-12-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
