# Generated by Django 3.1.4 on 2020-12-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_auto_20201208_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtuber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='media/ytubers/%Y/')),
                ('video_url', models.CharField(max_length=250)),
                ('discription', models.TextField()),
                ('age', models.IntegerField()),
                ('hight', models.IntegerField()),
                ('crew', models.CharField(max_length=250)),
                ('camera_type', models.CharField(max_length=250)),
                ('subs_count', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
