# Generated by Django 3.1.4 on 2020-12-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_youtuber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('canon', 'canon'), ('sony', 'sony'), ('red', 'red'), ('nikon', 'nikon'), ('fuji', 'fuji'), ('panasonic', 'panasonic'), ('other', 'other')], max_length=250),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('mobile_review', 'mobile_review'), ('cooking', 'cooking'), ('vloging', 'vloging'), ('gaming', 'gaming'), ('film', 'film'), ('comady', 'comady'), ('review', 'review')], max_length=250),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small', 'small'), ('large', 'large')], max_length=250),
        ),
    ]
