# Generated by Django 3.1.4 on 2020-12-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_youtuber_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='city',
            field=models.CharField(max_length=250),
        ),
    ]
